#!/bin/bash
#var1=10
#var2=20
#var3=`expr $var2 / $var1`
#echo the result is $var3

var1=100
var2=50
var3=45
var4=$[$var1 * ($var2 - $var3)]
var5=$[$var1 / $var3]
echo The final result is $var4
echo var5 is $var5

exit $var3
