#!/bin/bash

#trap "echo ' Sorry! I have trapped Ctrl-C '" SIGINT SIGTERM
trap "echo byebye" EXIT

count=1
while [ $count -le 5 ]
do
	echo "Loop #$count"
	sleep 3
	count=$[ $count + 1 ]
done
echo This is the end of the test program
