#!/bin/bash

exec 2>testerror

echo "This is a test of redirecting all output"
echo "from a script to another file."
echo "without having to redirect every individual line"

exec 1>testout

echo "This output should go to the testout file"
echo "but this should go to the testerror file" >&2
