#!/bin/bash

for file in /home/bob/source_code/linux_test_case/shell_test/*
do
	if [ -d "$file" ]
	then
	    echo "$file is  a directory"
	elif [ -f "$file" ]
	then
	    echo "$file is a file" 
	fi
done

for (( i=1; i <= 10; i++ ))
do
	echo "The next number is $i"
done

for (( a=1, b=10; a <= 10; a++, b-- ))
do
	echo "$a - $b"
done
