#!/bin/bash

val1=test
val2=''

if [ -n "val1" ]
then 
	echo "'$val1' is not empty"
fi

if [ -z "val2" ]
then 
	echo "the string '$val2' is empty"
else
	echo "the string '$val2' is not empty"
fi

if [ -z "val3" ]
then 
	echo "the string '$val3' is empty"
else
	echo "the string '$val3' is not empty"
fi
