#!/bin/bash

func1() {
    echo "trying to display a non-existent file"
    if sxx
    then
	wobuqu
    else
	???
    fi
    ls -l badfile
}

echo "testing the function: "
func1
echo "The exit status is: $?"


